/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "account-management_admins": () => import("@/views/account-management/admins/index.vue"),
  "account-management_branches": () => import("@/views/account-management/branches/index.vue"),
  "account-management_companies": () => import("@/views/account-management/companies/index.vue"),
  "account-management_restaurants": () => import("@/views/account-management/restaurants/index.vue"),
  "account-management_roles": () => import("@/views/account-management/roles/index.vue"),
  "account-management_users": () => import("@/views/account-management/users/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "menu-management_menu-categories": () => import("@/views/menu-management/menu-categories/index.vue"),
  "menu-management_menu-items": () => import("@/views/menu-management/menu-items/index.vue"),
  "menu-management_menu-served-dates": () => import("@/views/menu-management/menu-served-dates/index.vue"),
  "system-setting_access-controls": () => import("@/views/system-setting/access-controls/index.vue"),
  "system-setting_audits": () => import("@/views/system-setting/audits/index.vue"),
  "system-setting_backend-locales": () => import("@/views/system-setting/backend-locales/index.vue"),
  "system-setting_holiday-preferences": () => import("@/views/system-setting/holiday-preferences/index.vue"),
  "system-setting_locales": () => import("@/views/system-setting/locales/index.vue"),
  "system-setting_permissions": () => import("@/views/system-setting/permissions/index.vue"),
  "system-setting_selections": () => import("@/views/system-setting/selections/index.vue"),
  "system-setting_system-setting-types": () => import("@/views/system-setting/system-setting-types/index.vue"),
  "system-setting_system-settings": () => import("@/views/system-setting/system-settings/index.vue"),
};
