/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'account-management',
    path: '/account-management',
    component: 'layout.base',
    meta: {
      title: 'account-management',
      i18nKey: 'route.account-management',
      icon: 'mdi:account-cog-outline',
      order: 2
    },
    children: [
      {
        name: 'account-management_admins',
        path: '/account-management/admins',
        component: 'view.account-management_admins',
        meta: {
          title: 'account-management_admins',
          i18nKey: 'route.account-management_admins',
          icon: 'mdi:account-tie-outline',
          order: 2
        }
      },
      {
        name: 'account-management_branches',
        path: '/account-management/branches',
        component: 'view.account-management_branches',
        meta: {
          title: 'account-management_branches',
          i18nKey: 'route.account-management_branches',
          icon: 'mdi:source-branch',
          order: 4
        }
      },
      {
        name: 'account-management_companies',
        path: '/account-management/companies',
        component: 'view.account-management_companies',
        meta: {
          title: 'account-management_companies',
          i18nKey: 'route.account-management_companies',
          icon: 'mdi:domain',
          order: 3
        }
      },
      {
        name: 'account-management_restaurants',
        path: '/account-management/restaurants',
        component: 'view.account-management_restaurants',
        meta: {
          title: 'account-management_restaurants',
          i18nKey: 'route.account-management_restaurants',
          icon: 'mdi:storefront-outline',
          order: 5
        }
      },
      {
        name: 'account-management_roles',
        path: '/account-management/roles',
        component: 'view.account-management_roles',
        meta: {
          title: 'account-management_roles',
          i18nKey: 'route.account-management_roles',
          icon: 'mdi:shield-account-outline',
          order: 1
        }
      },
      {
        name: 'account-management_users',
        path: '/account-management/users',
        component: 'view.account-management_users',
        meta: {
          title: 'account-management_users',
          i18nKey: 'route.account-management_users',
          icon: 'mdi:account-group-outline',
          order: 6
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'menu-management',
    path: '/menu-management',
    component: 'layout.base',
    meta: {
      title: 'menu-management',
      i18nKey: 'route.menu-management',
      icon: 'mdi:food-outline',
      order: 4
    },
    children: [
      {
        name: 'menu-management_menu-categories',
        path: '/menu-management/menu-categories',
        component: 'view.menu-management_menu-categories',
        meta: {
          title: 'menu-management_menu-categories',
          i18nKey: 'route.menu-management_menu-categories',
          icon: 'mdi:shape-plus-outline',
          order: 1
        }
      },
      {
        name: 'menu-management_menu-items',
        path: '/menu-management/menu-items',
        component: 'view.menu-management_menu-items',
        meta: {
          title: 'menu-management_menu-items',
          i18nKey: 'route.menu-management_menu-items',
          icon: 'mdi:silverware-fork-knife',
          order: 2
        }
      },
      {
        name: 'menu-management_menu-served-dates',
        path: '/menu-management/menu-served-dates',
        component: 'view.menu-management_menu-served-dates',
        meta: {
          title: 'menu-management_menu-served-dates',
          i18nKey: 'route.menu-management_menu-served-dates',
          icon: 'mdi:calendar-range-outline',
          order: 3
        }
      }
    ]
  },
  {
    name: 'system-setting',
    path: '/system-setting',
    component: 'layout.base',
    meta: {
      title: 'system-setting',
      i18nKey: 'route.system-setting',
      icon: 'mdi:cog-outline',
      order: 3
    },
    children: [
      {
        name: 'system-setting_access-controls',
        path: '/system-setting/access-controls',
        component: 'view.system-setting_access-controls',
        meta: {
          title: 'system-setting_access-controls',
          i18nKey: 'route.system-setting_access-controls',
          icon: 'mdi:lock-outline',
          order: 6
        }
      },
      {
        name: 'system-setting_audits',
        path: '/system-setting/audits',
        component: 'view.system-setting_audits',
        meta: {
          title: 'system-setting_audits',
          i18nKey: 'route.system-setting_audits',
          icon: 'mdi:file-document-search-outline',
          order: 8
        }
      },
      {
        name: 'system-setting_backend-locales',
        path: '/system-setting/backend-locales',
        component: 'view.system-setting_backend-locales',
        meta: {
          title: 'system-setting_backend-locales',
          i18nKey: 'route.system-setting_backend-locales',
          icon: 'mdi:web',
          order: 7
        }
      },
      {
        name: 'system-setting_holiday-preferences',
        path: '/system-setting/holiday-preferences',
        component: 'view.system-setting_holiday-preferences',
        meta: {
          title: 'system-setting_holiday-preferences',
          i18nKey: 'route.system-setting_holiday-preferences',
          icon: 'mdi:calendar-check-outline',
          order: 9
        }
      },
      {
        name: 'system-setting_locales',
        path: '/system-setting/locales',
        component: 'view.system-setting_locales',
        meta: {
          title: 'system-setting_locales',
          i18nKey: 'route.system-setting_locales',
          icon: 'mdi:translate',
          order: 2
        }
      },
      {
        name: 'system-setting_permissions',
        path: '/system-setting/permissions',
        component: 'view.system-setting_permissions',
        meta: {
          title: 'system-setting_permissions',
          i18nKey: 'route.system-setting_permissions',
          icon: 'mdi:key-chain-variant',
          order: 1
        }
      },
      {
        name: 'system-setting_selections',
        path: '/system-setting/selections',
        component: 'view.system-setting_selections',
        meta: {
          title: 'system-setting_selections',
          i18nKey: 'route.system-setting_selections',
          icon: 'mdi:format-list-bulleted-square',
          order: 5
        }
      },
      {
        name: 'system-setting_system-setting-types',
        path: '/system-setting/system-setting-types',
        component: 'view.system-setting_system-setting-types',
        meta: {
          title: 'system-setting_system-setting-types',
          i18nKey: 'route.system-setting_system-setting-types',
          icon: 'mdi:shape-outline',
          order: 4
        }
      },
      {
        name: 'system-setting_system-settings',
        path: '/system-setting/system-settings',
        component: 'view.system-setting_system-settings',
        meta: {
          title: 'system-setting_system-settings',
          i18nKey: 'route.system-setting_system-settings',
          icon: 'mdi:tune-variant',
          order: 3
        }
      }
    ]
  }
];
